import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models/session.dart';

class PdfService {
  static Future<void> exportSession(Session session) async {
    final pdf = pw.Document();
    final dateStr = DateFormat('dd MMM yyyy – HH:mm').format(session.startedAt);
    final duration = _formatDuration(session.duration);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(session.topicTitle, dateStr),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          _buildStats(session, duration),
          pw.SizedBox(height: 20),
          if (session.vocabulary.isNotEmpty) ...[
            _sectionTitle('Vocabulary'),
            pw.SizedBox(height: 8),
            _buildVocabularyTable(session),
            pw.SizedBox(height: 20),
          ],
          _sectionTitle('Conversation Transcript'),
          pw.SizedBox(height: 8),
          _buildTranscript(session),
        ],
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename:
          'talkie_${session.topicId}_${DateFormat('yyyyMMdd_HHmm').format(session.startedAt)}.pdf',
    );
  }

  static pw.Widget _buildHeader(String topic, String date) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 12),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: PdfColors.blue700, width: 2),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Talkie — English Session',
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blue700,
                ),
              ),
              pw.SizedBox(height: 2),
              pw.Text(
                topic,
                style: const pw.TextStyle(
                  fontSize: 12,
                  color: PdfColors.grey700,
                ),
              ),
            ],
          ),
          pw.Text(
            date,
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          top: pw.BorderSide(color: PdfColors.grey300),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Talkie',
              style:
                  const pw.TextStyle(fontSize: 9, color: PdfColors.grey500)),
          pw.Text('Page ${context.pageNumber} / ${context.pagesCount}',
              style:
                  const pw.TextStyle(fontSize: 9, color: PdfColors.grey500)),
        ],
      ),
    );
  }

  static pw.Widget _buildStats(Session session, String duration) {
    final exchanges =
        session.messages.where((m) => m.role == 'user').length;
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue50,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
        children: [
          _statCell('Duration', duration),
          _statCell('Exchanges', '$exchanges'),
          _statCell('Words learned', '${session.vocabulary.length}'),
        ],
      ),
    );
  }

  static pw.Widget _statCell(String label, String value) {
    return pw.Column(
      children: [
        pw.Text(value,
            style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.blue700)),
        pw.SizedBox(height: 2),
        pw.Text(label,
            style:
                const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
      ],
    );
  }

  static pw.Widget _sectionTitle(String title) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 10),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue700,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          color: PdfColors.white,
          fontWeight: pw.FontWeight.bold,
          fontSize: 13,
        ),
      ),
    );
  }

  static pw.Widget _buildVocabularyTable(Session session) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      columnWidths: {
        0: const pw.FlexColumnWidth(1.5),
        1: const pw.FlexColumnWidth(2),
        2: const pw.FlexColumnWidth(2.5),
        3: const pw.FlexColumnWidth(1.5),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.blue100),
          children: ['Word', 'Definition', 'Example', 'French']
              .map((h) => pw.Padding(
                    padding: const pw.EdgeInsets.all(6),
                    child: pw.Text(h,
                        style: pw.TextStyle(
                            fontWeight: pw.FontWeight.bold, fontSize: 10)),
                  ))
              .toList(),
        ),
        ...session.vocabulary.map(
          (v) => pw.TableRow(
            children: [v.word, v.definition, v.exampleSentence, v.translation]
                .map((cell) => pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(cell,
                          style: const pw.TextStyle(fontSize: 9)),
                    ))
                .toList(),
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildTranscript(Session session) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: session.messages.map((msg) {
        final isUser = msg.role == 'user';
        return pw.Container(
          margin: const pw.EdgeInsets.only(bottom: 8),
          padding: const pw.EdgeInsets.all(10),
          decoration: pw.BoxDecoration(
            color: isUser ? PdfColors.grey100 : PdfColors.blue50,
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
          ),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.SizedBox(
                width: 40,
                child: pw.Text(
                  isUser ? 'You' : 'Alex',
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: isUser ? PdfColors.grey700 : PdfColors.blue700,
                  ),
                ),
              ),
              pw.SizedBox(width: 8),
              pw.Expanded(
                child: pw.Text(
                  msg.text,
                  style: const pw.TextStyle(fontSize: 10, lineSpacing: 2),
                ),
              ),
            ],
          ),
        );
      }).toList(),
    );
  }

  static String _formatDuration(Duration d) {
    final m = d.inMinutes;
    final s = d.inSeconds % 60;
    return '${m}m ${s}s';
  }
}
